class District {
  String name;

  District({this.name});
}

List<District> districtList = [
  District(name: "Bagerhat"),
  District(name: "Bandarban"),
  District(name: "Barguna"),
  District(name: "Barishal"),
  District(name: "Bhola"),
  District(name: "Bogura"),
  District(name: "Brahmanbaria"),
  District(name: "Chandpur"),
  District(name: "Chapai Nawabganj"),
  District(name: "Chattogram"),
  District(name: "Chuadanga"),
  District(name: "Cox's Bazar"),
  District(name: "Cumilla"),
  District(name: "Dhaka"),
  District(name: "Dinajpur"),
  District(name: "Faridpur"),
  District(name: "Feni"),
  District(name: "Gaibandha"),
  District(name: "Gazipur"),
  District(name: "Gopalganj"),
  District(name: "Habiganj"),
  District(name: "Jamalpur"),
  District(name: "Jashore"),
  District(name: "Jhalakathi"),
  District(name: "Jhenaidah"),
  District(name: "Joypurhat"),
  District(name: "Khagrachhari"),
  District(name: "Khulna"),
  District(name: "Kishoreganj"),
  District(name: "Kurigram"),
  District(name: "Kushtia"),
  District(name: "Lakshmipur"),
  District(name: "Lalmonirhat"),
  District(name: "Madaripur"),
  District(name: "Magura"),
  District(name: "Manikganj"),
  District(name: "Meherpur"),
  District(name: "Moulvibazar"),
  District(name: "Munshiganj"),
  District(name: "Mymensingh"),
  District(name: "Naogaon"),
  District(name: "Narail"),
  District(name: "Narayanganj"),
  District(name: "Narsingdi"),
  District(name: "Natore"),
  District(name: "Netrakona"),
  District(name: "Nilphamari"),
  District(name: "Noakhali"),
  District(name: "Pabna"),
  District(name: "Panchagarh"),
  District(name: "Patuakhali"),
  District(name: "Pirojpur"),
  District(name: "Rajbari"),
  District(name: "Rajshahi"),
  District(name: "Rangamati"),
  District(name: "Rangpur"),
  District(name: "Satkhira"),
  District(name: "Shariatpur"),
  District(name: "Sherpur"),
  District(name: "Sirajganj"),
  District(name: "Sunamganj"),
  District(name: "Sylhet"),
  District(name: "Tangail"),
  District(name: "Thakurgaon"),
];
